# Velocity scale
Parfile.ins_inflowVelScale = 1.0

# Gravity
Parfile.ins_gravX = -0.0001

# Restart, checkpoint, and plotting options
Parfile.nend = 10000000
Parfile.tmax = 200.0
Parfile.restart = ".false."
Parfile.checkpointFileNumber = 0
Parfile.checkpointFileIntervalTime = 5.0
Parfile.plotFileNumber = 0
Parfile.plotFileIntervalTime = 1.0
